---
title: "Johnstone Tcheou"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 

Hi there - my name is Johnstone Tcheou. I'm a second year MPH student at Columbia University - Mailman School of Public Health, studying epidemiology. My interests include infectious disease epidemiology and biostatistical methods. This summer, I interned with the [NYC DOHMH](https://www.nyc.gov/site/doh/about/about-doh.page) with the Bureau of Epidemiology Services to estimate the NYC population by various geographies of borough, ZIP code tabulation area, and neighborhood tabulation area. I currently work with the [Mathema Lab](https://www.publichealth.columbia.edu/profile/barun-mathema-phd) at Mailman, looking at antimicrobial resistance and transmission in tuberculosis.

Before Columbia, I was most recently a research assistant at the [Krammer Lab](https://labs.icahn.mssm.edu/krammerlab/) at Icahn School of Medicine at Mount Sinai. Prior to that, I was an intern with Broadstreet at the [COVID-19 Data Project](https://covid19dataproject.org/), collecting and QCing weekly COVID-19 case and death counts by county for the Midwest. Even before that, I was a case investigator for COVID-19 with the [NYC Health and Hospitals Test & Trace Corps](https://www.nyc.gov/site/coronavirus/get-tested/test-trace-corps.page). 

My GitHub is available [here](http://github.com/tcheouj>/). If you'd like to look at some papers I was previously involved in, my ResearchGate is available [here](https://www.researchgate.net/profile/Johnstone-Tcheou). My LinkedIn is also accessible [here](https://www.linkedin.com/in/jtcheou/). All of these links are also available through the navigation bar.
